// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCTKAlQsAbXHZsPl3thqIkd149HLom5atI',
    appId: '1:654830286824:web:92476bba15266a4e00965d',
    messagingSenderId: '654830286824',
    projectId: 'evaluacion-20850',
    authDomain: 'evaluacion-20850.firebaseapp.com',
    storageBucket: 'evaluacion-20850.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZkl1x1SSW7aOBkGxZG8vndhm0EsoXLxc',
    appId: '1:654830286824:android:bffc6da8e9bee06b00965d',
    messagingSenderId: '654830286824',
    projectId: 'evaluacion-20850',
    storageBucket: 'evaluacion-20850.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAv5t9qjRhtWV84UuGYvaXAhHtBW3TTSdA',
    appId: '1:654830286824:ios:099f276f86f93df700965d',
    messagingSenderId: '654830286824',
    projectId: 'evaluacion-20850',
    storageBucket: 'evaluacion-20850.appspot.com',
    iosClientId: '654830286824-h47i1a0sbbbvaoafd4digl0rmmqvb4rd.apps.googleusercontent.com',
    iosBundleId: 'com.example.login',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAv5t9qjRhtWV84UuGYvaXAhHtBW3TTSdA',
    appId: '1:654830286824:ios:50fe625a741875bb00965d',
    messagingSenderId: '654830286824',
    projectId: 'evaluacion-20850',
    storageBucket: 'evaluacion-20850.appspot.com',
    iosClientId: '654830286824-iknsh041cjqasp2to8k316ndeqhpp50u.apps.googleusercontent.com',
    iosBundleId: 'com.example.login.RunnerTests',
  );
}
